sudo: false
language: ruby
services:
  - mysql
addons:
  postgresql: "9.6"
rvm:
  - 2.5.8
  - 2.6.6
env:
  - RAILS=6-0 DB=sqlite
  - RAILS=6-0 DB=pg
  - RAILS=6-0 DB=mysql
  - RAILS=5-2 DB=sqlite
  - RAILS=5-2 DB=pg
  - RAILS=5-2 DB=mysql
before_script:
  - psql -c 'create database active_reporting_test;' -U postgres
  - mysql -e 'create database active_reporting_test collate utf8_general_ci;'
